const data = {
  products: [
    {
      // _id: '1',
      name: 'Baar Chair',
      slug: 'baar chair',
      category: 'Chairs',
      image: '/images/p1.jpg', // 679px × 829px
      price: 400,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality chair',
    },
    {
      // _id: '2',
      name: 'Executive Chair',
      slug: 'executive chair',
      category: 'Chairs',
      image: '/images/p2.jpg',
      price: 300,
      countInStock: 0,
      rating: 4.8,
      numReviews: 15,
      description: 'high quality chair',
    },
    {
      // _id: '3',
      name: 'Mesh Chair',
      slug: 'mesh chair',
      category: 'Chairs',
      image: '/images/p3.jpg',
      price: 450,
      countInStock: 20,
      rating: 5.0,
      numReviews: 14,
      description: 'high quality chair',
    },
    {
      // _id: '4',
      name: 'Visitors Chair',
      slug: 'visitors chair',
      category: 'Chairs',
      image: '/images/p4.jpg',
      price: 500,
      countInStock: 15,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality chair',
    },
    {
      // _id: '5',
      name: 'Workstation Chair',
      slug: 'workstation chair',
      category: 'Chairs',
      image: '/images/p6.jpg',
      price: 150,
      countInStock: 50,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality chair',
    },
    {
      // _id: '6',
      name: 'Waiting Lounge',
      slug: 'Waiting Lounge',
      category: 'Chairs',
      image: '/images/p5.jpg',
      price: 8000,
      countInStock: 50,
      rating: 4.8,
      numReviews: 12,
      description: 'high quality chair',
    },
  ],
};
export default data;
